### ISSUE TITLE
[Triage] Cannot connect to VS Code 405 method not allowed

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1363]
From customer:

For any new Compute Instances created after sometime yesterday, I'm can't connect to the CI using websocket experience.

I've tried multiple VSCode instances (locally on Mac and in Windows VM) and multiple Azure tenants - I can connect to CIs created Wednesday, but not to VMs created yesterday afternoon. 

The error I'm getting is:

[Error - 2021-11-05 14:57:50.459] Invalid response: 405 Method Not Allowed
[Error - 2021-11-05 14:57:50.459] Cannot communicate with the Jupyter endpoint.

Behavior seen in other subscriptions.

**Comment by saksham1211** [comment]
Hi, I am also facing the same issue
any leads on what is happening exaclty?

**Comment by abi-alejandro-aristizabal** [comment]
Hi, I have run into the same issue. I have un- and re- installed VS Code and created a new compute instance too. However, nothing seems to work.

**Comment by sevillal** [comment]
@saksham1211, @abi-alejandro-aristizabal sorry for the inconvenience, we are working fix that will be released shortly, potentially today. I will keep you updated.

**Comment by sevillal** [comment]
@saksham1211 @abi-alejandro-aristizabal we have released version 0.6.27 of the extension, please upgrade and retry the connection. Let me know if you face any issue.

**Comment by ant0nsc** [comment]
@sevillal  I was facing the same issue. My VSCode was claiming that it had version 0.6.27 installed, but still failed to connect to my compute instance. I then uninstalled the extension, re-installed, and from that moment on it worked.

**Comment by saksham1211** [comment]
> @saksham1211 @abi-alejandro-aristizabal we have released version 0.6.27 of the extension, please upgrade and retry the connection. Let me know if you face any issue.

@sevillal Thank you so much, now it is working like charm. Great Work!

**Comment by sevillal** [comment]
Thanks @ant0nsc for sharing that. I have created a different issue to track that behavior. Will be updating that one with any findings.

https://github.com/microsoft/vscode-tools-for-ai/issues/1369
