### ISSUE TITLE
Connect to compute instance failed with Websocket error

### ISSUE THREAD

**Issue by olihofmann** [microsoft/vscode-tools-for-ai#1525]
## Expected Behavior
In the Machine Learning Studio you can click on VS Code at the desired compute instance and a websocket connection will be established and you can then work remotely.

## Actual Behavior
Since Friday, the problem occurs that no remote connection can be established via VS code. It comes an error "cannot fetch remote environment WebSocket close with error 1006".

## Steps to Reproduce the Problem

  1. Go to ML Studio
  2. Go to the compute instances
  3. Klick on VS Code

## Specifications

  - VS Code Version: 1.66
  - Platform: Windows 11
  - Azure Machine Learning - Remote: v0.10.0

**Comment by shreymehtaqrg** [comment]
We are experiencing the same issue. We already have all the firewalls in place as documented here - https://docs.microsoft.com/en-us/azure/machine-learning/how-to-access-azureml-behind-firewall?tabs=ipaddress%2Cpublic#visual-studio-code-hosts

**Comment by shsuman** [comment]
@tbombach Can you please look into this issue ?

**Comment by MarkusDressel** [comment]
Same here.

**Comment by shsuman** [comment]
@olihofmann @shreymehtaqrg @MarkusDressel Can you please share the **Trace** logs with us ? 

You can enable **Trace** logging by changing the settings azureML - Remote.logging.level to **trace**

![image](https://user-images.githubusercontent.com/44413557/161809386-9dd36d4e-3a50-4b01-98e0-72cf977c09cb.png)

Then just try to make a remote connection in the VSCode window and after it fails, open the output channel (Ctrl + Shift + U or View -> Output), and select the **Azure ML - Remote** output:

![image](https://user-images.githubusercontent.com/44413557/161811181-abc0a190-a968-4955-8d5b-e41923898c30.png)

**Comment by shreymehtaqrg** [comment]
How do you want me to share the output, it does contain urls for my instance names. Is their a secured way to share the error?

From: Shantnu Suman ***@***.***>
Sent: Tuesday, April 5, 2022 1:05 PM
To: microsoft/vscode-tools-for-ai ***@***.***>
Cc: Shrey Mehta ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/vscode-tools-for-ai] Connect to compute instance failed with Websocket error (Issue #1525)

This email is from an external sender.  If you think it is malicious or spam, please do not open any attachments or links and click the Report Phishing button.


@olihofmann<https://secure-web.cisco.com/1eJTlVkX0xoLGuG-n79ZkAnvpc0Y-J7LrU9FvgGX_Q-nHikatfWtzjmnZYNPVMR1hVSuBz6mQkdzn9yvkYWurV6AbwTXKvs3a3AJakSxr7RdNWfCUxMr5xQAxoBwMUXSakFHO1bHrdXlkNRNoUgqZI04hT_5vqflpQXharpgLzm8sP0h4v5Zdi2VS4mPORQXUsl_hk3HIdGehjjIVrnnrTxuNjccy4wY_pRVZ8NqeCSp5A3dt3AqVOIqAf-asl3OSip3EuKz9OOlLpUPBmF4PPpThLi7uAw76kDZcWj5k4jl5X_PJDPftzFZNCvC13UYt6mPCnk9GnsnseYtRgB_WN2An-rrkYSWlr9EP8ui74buCaMRfVFaTHzwUjAoFgQZBzOfjgijasmBPLV34C-2637AhWZ6zzb7_qzDPmv_pfG3tfy3Sdj5C6QmsJKMxvAFf/https%3A%2F%2Fgithub.com%2Folihofmann> @shreymehtaqrg<https://secure-web.cisco.com/12SxAj1rZ6TNycgQRWhEpCDJFEaOhvO-gJuwHtingTbrOdMdXarpqzX_MgptVWQBiUOkGjZXufpioGCcr7_wbCI1BYCefKtxjPWFoiDD4xRzgNPIbApJgVNetwiMKObtBOT_JHdS3-S7iWhc_FhcPcnahxIkoC7Sr4kyFb5Sc35G9HWag2G_v4uGlqVsGJ4MCU4YNGeASOpp1SwgdddHxawYL6ET38DUhMa7uNQ9wrkrBsrjhEJ1Nv7C_RpBEmLEYx_9Ww7ot7REKwnNUCpePgqlzl994JWba6RcZ34rMUM6JgarVlZ3BtxvGlBwoM27eY279_mJNxgT2-f6KFGA7FuMvYdSb_F1zTclMdL1FoIYrWffiu-81f0JbU00DQxLlnFoKaaTaYnfJ9HGNia0e9lRTPFm2COGYrfK2va_1zYWrttSGHeIfVENSTxCanJMM/https%3A%2F%2Fgithub.com%2Fshreymehtaqrg> @MarkusDressel<https://secure-web.cisco.com/1iwLKt0svNQE6sWS17yrDi48oC3rZ9V7JrlYyW0TT-H41ZvQFUKWtN05uWNLpu_S_pdHEx4-1FdFccjGsrhlGdVo06D5zq0OrIQIthJjH8G7EvCru5HGlq7BTKJQum6vHo1j9jxs8Phvxqs4NwwNjlxdpJ7g6d8JaCPFRMFOu04WvpZE5MgTDZ6v5EbW2LsQvCB6csqHYYFrGTKBkDDuNh_qUVFJV8YseHfbUZRcdxVoZfU_HOF1RuCIfyHn0Gby0TtZGIbTrYBUpoZsnm9hoOFMCzRNKfxfNW84gUm-8zoTB7YRYMAwSQcnVzGAiialRSj3N8c_3agdaE6-KNI9gsZ4_kCop4tv2UE0LwNb0UVWgTvn3-Z1Yb17mgwrVCstG_ZEsEsEtcAq5rQK51zdnUUPKx-GR19CcCn7spFvtJT8-tDF1aJ4AU14UOFN2T7HH/https%3A%2F%2Fgithub.com%2FMarkusDressel> Can you please share the Trace logs with us ?

You can enable Trace logging by changing the settings azureML - Remote.logging.level to trace

[image]<https://secure-web.cisco.com/1YTkU239AwE7gOjnbE5vY9A4cb5Z2nRON2bcDja8tXA7DAZiUnuFVgcm85rTrrJa5jr1H00BR1R2lSIky3vaOf_Xr1-nJYYZGPsTCgSeq25wySq3Kfpx_SHg2i93ZwAdTi5ucbd0AMpZdsy_lZlVEgtHoio5FZu76preZ5DXXmrmqjRWcFgvIdfyGINWmY_yCKHhFaEVjjK4BBqbf5IPEms0TZF_LUIbhWrvO0aQ59rc5aBldhqhsy1MQfZnHPnAGEz9DItTGUYQMLTsHDjHxChJu38zeNw3T1xWwM5SuQxBHewwKBpJUyWCGaLuLOSqEAqfwWpdFGg21CeK-hZ_NOE65lto1Ie0GHDfszExEx2Zk3-z2tFCVq5tId9iUDKjT6hWcPaMgrMrf93-1QBHwxXWt7J9SsMLegJlTdnZVdVFbQ78yqE42UCKOfPiTAS0z/https%3A%2F%2Fuser-images.githubusercontent.com%2F44413557%2F161809386-9dd36d4e-3a50-4b01-98e0-72cf977c09cb.png>

Then just try to make a remote connection in the VSCode window and after it fails, open the output channel (Ctrl + Shift + U or View -> Output), and select the Azure ML - Remote output:

[image]<https://secure-web.cisco.com/1MyjP66v1f8Rtd_3lgjLgquL6kZWe_vEU-sslhKqmVUYGDq6CtrPgf3Hr-pMnwhWXI0umbj4l0ayxgSiNRBd25avG8O6H31mXYXP6gy8OOzScpGZRi7tzBRGNI_aLQb9vtr6wnY0jS3GNnAWIRB9JttDaRuYZCFpRnj1Yvjq6AcvkW3sDR_K4NFsfMtSNg0pw4P8otwJVtFvH7uK6zE0B7ARgPRUY4QF2yE5_SjYou9M891cHkAwISi-sYDUlRM91gl1hHBWj47qdsINUSv3LSgjKQhIFlXYzgBuCnAGoHBWheu6HHM_bGVpHGIO01W4sw26opZ1Y9_95fi-mN8AXpCoDeFpV6HsdR9LQ3XsWG7pXwWzHDsIMtlYZ2MSEiXWRdvfPW-IxGIJ78JtW_1DI5-f6ij4HN19pXabjCK0swBGsrchaq0rlZbU7Cc1pUecY/https%3A%2F%2Fuser-images.githubusercontent.com%2F44413557%2F161811181-abc0a190-a968-4955-8d5b-e41923898c30.png>

**Comment by shsuman** [comment]
@shreymehtaqrg you can redact any PII or sensitive information. The logs does react tokens but there will be PII such as URLs and filepaths.

**Comment by shsuman** [comment]
Alternatively, you can send it to my email: shsuman@microsoft.com

**Comment by MarkusDressel** [comment]
@shsuman send my trace log to you email.

**Comment by shsuman** [comment]
Hello @MarkusDressel @olihofmann @shreymehtaqrg, Just a couple of questions:

1. Can you downgrade our extensions (Azure Machine Learning - 0.6.28 and Azure Machine Learning -  Remote - 0.8.0) and check whether the connection works for you ? To downgrade VSCode extensions, you can follow the instructions [here](https://code.visualstudio.com/updates/v1_30#_install-previous-versions).
2. Also, are you using a proxy ?

NOTE: If you are stuck in a broken remote window, you can run the command `Close Remote Connection` using (Ctrl + Shift + P, Cmd + Shift + P) to get out into a fresh window

**Comment by olihofmann** [comment]
@shsuman I have downgrade the both extensions and the connection to the compute cluster works

**Comment by MarkusDressel** [comment]
@shsuman yes, that works

**Comment by shsuman** [comment]
@olihofmann @MarkusDressel, This is indeed a long shot but can you try to upgrade the extensions to latest versions(Azure ML - 0.8.1, Azure ML - Remote - 0.10.0) and try again ? We released a patch yesterday for other issues we were seeing with 0.8.0 but since I am not sure at this point how can that affect you, I guess it doesn't hurt to try :)

**Comment by olihofmann** [comment]
@shsuman here the output from the diagnostic report
`
********************************************************************************
Diagnostic Report: Connect to remote target
********************************************************************************

Client Information
================================================================================
Quality: stable
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5

VS Code Servers
================================================================================
Installed versions count: 1

Commit e18005f0f1b33c29e81d732535d8c0e47cafb0b5
--------------------------------------------------------------------------------
Status: Not Running

PID: 23182

Processes:
azureus+ 23182     1  0 07:07 ?        S      0:00 sh /home/azureuser/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/bin/code-server --start-server --host=127.0.0.1 --accept-server-license-terms --without-connection-token --enable-remote-auto-shutdown --port=0
azureus+ 23192 23182  0 07:07 ?        Sl     0:00 /home/azureuser/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/node /home/azureuser/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/server-main.js --start-server --host=127.0.0.1 --accept-server-license-terms --without-connection-token --enable-remote-auto-shutdown --port=0
azureus+ 23203 23192  0 07:07 ?        Sl     0:00 /home/azureuser/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/node /home/azureuser/.vscode-server/bin/e18005f0f1b33c29e81d732535d8c0e47cafb0b5/out/bootstrap-fork --type=ptyHost

Log:
*
* Visual Studio Code Server
*
* By using the software, you agree to
* the Visual Studio Code Server License Terms (https://aka.ms/vscode-server-license) and
* the Microsoft Privacy Statement (https://privacy.microsoft.com/en-US/privacystatement).
*
Server bound to 127.0.0.1:37513 (IPv4)
Extension host agent listening on 37513

[07:07:28] Extension host agent started.
[07:07:29] Deleted from disk ms-toolsai.vscode-ai /home/azureuser/.vscode-server/extensions/ms-toolsai.vscode-ai-0.8.0

Listening port: 37513

lsof output:
COMMAND   PID      USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
node    23192 azureuser   18u  IPv4 328474      0t0  TCP localhost:37513 (LISTEN)

Azure ML Websocket Servers
================================================================================
Installed versions count: 1

Version v0.2
--------------------------------------------------------------------------------
Status: Running

Processes:
azureus+ 24267     1  0 07:07 ?        S      0:00 sh /home/azureuser/.azureml_remote_websocket_server/bin/v0.2/server.sh --port=0 --vscode-server-port=37513 --commit=e18005f0f1b33c29e81d732535d8c0e47cafb0b5
azureus+ 24274 24267  0 07:07 ?        Sl     0:00 /home/azureuser/.azureml_remote_websocket_server/bin/v0.2/node /home/azureuser/.azureml_remote_websocket_server/bin/v0.2/dist/server/azureMLRemoteAgent.js --port=0 --vscode-server-port=37513 --commit=e18005f0f1b33c29e81d732535d8c0e47cafb0b5

PID files:
  File: .stable.e18005f0f1b33c29e81d732535d8c0e47cafb0b5.v0.2.pid
  PID: 24267

LOG files:
  File: .stable.e18005f0f1b33c29e81d732535d8c0e47cafb0b5.v0.2.log
  LOG:
Azure ML websocket server listening on 8889


[07:07:30] Azure ML websocket server started

Listening port: 8889

lsof output:
COMMAND   PID      USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
node    24274 azureuser   19u  IPv6 332149      0t0  TCP *:8889 (LISTEN)
`

**Comment by shsuman** [comment]
@olihofmann, @MarkusDressel, @shreymehtaqrg Are you all using private link enabled workspaces? I was comparing all of your logs to see some common pattern and I found that the extension infers that you all are in private link enabled workspaces.

Can you please share your workspace properties with me by following the steps below:
1. Go to the extension tree view (Shift + Alt + A)
2. Expand on your subscription node
3. Right click on your workspace (the one which contains your Compute instances) and click `View Properties`
4. You will see a YAML file open in the editor. Please share the contents of the YAML file

![image](https://user-images.githubusercontent.com/44413557/161925814-1cf1a4d1-4202-4d8d-9a92-3b4f5871bd9a.png)
![image](https://user-images.githubusercontent.com/44413557/161926075-7e14a897-884d-4055-ad1e-4c92a80d0576.png)

**Comment by olihofmann** [comment]
We are using a private link enabled workspace. I will send you the file by mail

**Comment by shsuman** [comment]
@olihofmann Thank you so much for sharing all this. I have a working theory where the error might be coming from now. Can you just do one more thing and send me the Azure ML - Remote trace logs of the downgraded extensions. So, downgrade the extensions and initiate a successful remote connection and share the logs of that connection :). Once, I get the logs, I can validate my hypothesis and if true, we can release a fix ASAP :)

**Comment by olihofmann** [comment]
@shsuman I send you the trace log by email

**Comment by shsuman** [comment]
Thanks @olihofmann. The error is the same which I suspected. I will start working on the fix and we will try to release it ASAP. In the meantime, please continue using the extension by downgrading the versions

**Comment by olihofmann** [comment]
@shsuman thanks for the great support

**Comment by shsuman** [comment]
Closing this issue as it has been fixed by 0.8.2  release. Please reopen if need be :)

**Comment by shreymehtaqrg** [comment]
We are still facing issues, I have sent out an email with details on this issue. 
We are using the latest versions of extensions and our AML workspace is Private Link enabled

**Comment by shsuman** [comment]
Reopening this as @shreymehtaqrg and his team is still facing the issue. Following up on Azure ML CSS mail thread.

**Comment by shreymehtaqrg** [comment]
Yes we can now successfully connect from inside the VNet. Feel free to close the ticket.

Thanks for your support

From: Sergio Villalobos ***@***.***>
Sent: Monday, June 13, 2022 2:15 PM
To: microsoft/vscode-tools-for-ai ***@***.***>
Cc: Shrey Mehta ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [microsoft/vscode-tools-for-ai] Connect to compute instance failed with Websocket error (Issue #1525)

This email is from an external sender.  If you think it is malicious or spam, please do not open any attachments or links and click the Report Phishing button.


@shreymehtaqrg<https://secure-web.cisco.com/1w-Yqda4z96a2m7ELQnVulv8EWbc_lNqUwOmbX5vVrFThKBLNZTlNwnCau5t7sBIpxzsgk3KzcXLp6MDxoPREPzJxZqxeBhJ64fe2lNlwHupcjLXqyBFirVQj5w0I8cjVPJrV-7mW0gZ5y96EZl6ufeDmSLW3X0QUoZOZATdJpLKx9YOd0BFbmHKrwMkyvdy4D0tu17ifN4svCJkC2dEaUNMJAVUFnJGWNK9bZjF5qgmRdCPZNJmBkVOObH6KmlAtrsUcRUGMORi8TQW3SmoGfx9rqKsR2OsgZvF_xRu3WMlDT0r7fiOdeJz-C3E_WdwEVIYHnL8GPDDiyA7isJ38M3JXsTds7Fg-Nsbd0CV14uP6ax6rVqIVouMTB5-fqXbJhXS1GtwK4b0vpUo-j3DjelQO61m1xVX6ALmypM4RNVwTMOqrSYm5Y8fAT7Hcs4TXYSfR7f5XYtM3dOdYRNKJYw/https%3A%2F%2Fgithub.com%2Fshreymehtaqrg> are you still facing this issue? Have you been able to connect from inside the vnet?

Closing this for now, please reopen if needed.
